# Generated by Django 3.1.6 on 2021-02-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210210_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='covidVaccinationData',
            new_name='VaccinationData',
        ),
    ]
